# syntax=docker/dockerfile:1

FROM azul/zulu-openjdk:18.0.1-18.30.11

WORKDIR /

# Copy all files and folders to the build directory
COPY . ./

# Test, Compile & Run
ENTRYPOINT ["./mvnw", "spring-boot:run"]


